
- name: installing core packages
  become: yes
  apt:
    name:
      - sudo
      - supervisor
      - git
      - python-pip
      - python-dev
      - python3-pip
      - python-apt
      - virtualenv
      - python-psycopg2
      - libsqlite3-dev
      - python3-dev
      - libpq-dev
      - postgresql
      - postgresql-contrib
      - nginx
      - acl #enable to enable access to tmp files for non-root users
    state: present
    autoclean: yes

- name: Creates virtualenvs directory
  file:
    path: /home/{{deployer_user}}/.virtualenvs
    state: directory
    owner: "{{ deployer_user }}"

- name: Creates log directory
  file:
    path: "{{ log_dir }}"
    state: directory
    owner: "{{ deployer_user }}"
